name: Java CI with Maven

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'zulu'
    - name: Run Spotless check
      run: mvn spotless:check
    - name: Create WAR
      run: mvn package
    - name: blackduck scan
      run: bash <(curl -s https://detect.synopsys.com/detect9.sh)
        --blackduck.url=https://bdscan.i.mercedes-benz.com/
        --blackduck.api.token="${{secrets.BLACKDUCK_API_TOKEN}}"
        --detect.project.name="${{ env.bd-project}}"
        --detect.project.version.name="${env.version}}"
        --detect.code.location.name="${{ env.bd-project}}"-"${{env.version}}"
